server:
  port: 10000

spring:
  application:
    name: ex10
  # sql ?? ????
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.40:3306/pmh
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false
    # ????? ?? ? ?? data.sql ? ?? insert ?? ????
    defer-datasource-initialization: true

my:
  value: "welcome to my value"