server:
  port: 20000

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.40:30306/msa?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  output:
    ansi:
      enabled: always

  # zipkin:
  #   base-url: http://localhost:9411
  #   enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: false
    show-sql: true
    open-in-view: false

# sql:
#   init:
#     platform: mysql

mh:
  value: "abcdefg"


management:
  endpoints:
    web:
      exposure:
        include: "*"

token:
  access_token_expiration_time: 86400 # 하루
  refresh_token_expiration_time: 2592000 # 한달
  secret: abcdefghijklmnopqrstuvwxyz01234567890

gateway:
  ip: 127.0.0.1

first-service-url: http://localhost:40001
order-service-url: http://localhost:20001