apiVersion: apps/v1
kind: Deployment # pod 여러개
metadata:
  name: order-service-deployment
spec: # 어떻게 만들지 대한 내용
  replicas: 1 # 몇개의 pod 만들래?
  selector:
    matchLabels:
      app: order-service # 쿠버네티스 안에서 변수명
  template:
    metadata:
      labels:
        app: order-service # 서비스에서 찾는 변수명
    spec: # pod 하나하나에 대한 내용
      containers:
        - name: order-service
          image: finnnnnn/user-service:msa.k8.01  # dockerhub 에 있는 image
          ports:
            - containerPort: 40003 #default one
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: spring-datasource-url-user
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: spring-datasource-username
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: user-service-port
            - name: FIRST_SERVER_PORT
              value: first-service:40001
            - name: ORDER_SERVER_PORT
              valueFrom: order-service:40001
---
apiVersion: v1
kind: Service
metadata:
  name: orderorder-service
spec:
  type: LoadBalancer
  ports:
    - port: 40003
      targetPort: 40003
  selector:
    app: order-service